# eslint-disable no-irregular-whitespace, yaml/no-irregular-whitespace
# prettier-ignore
name:  

on:
  workflow_call:
    inputs:
      ref:
        description: "Force checkout a specific git ref (branch, tag, commit)"
        type: string

concurrency:
  group: deploy
  cancel-in-progress: false # canceling could break state

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: pnpm install
        uses: falcondev-it/.github/actions/pnpm-install@master

      - name: build
        run: pnpm run build

      - name: configure npm auth
        run: cat <<EOF > .npmrc
          //registry.npmjs.org/:_authToken=${NPM_TOKEN}
          registry=https://registry.npmjs.org/
          EOF

      - name: Publish
        run: pnpm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
